# Netlify Build Configuration
[build]
  command = "npm run build"
  publish = "dist"

# Fix React Router issue (SPA redirect to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

